---
title: "Label Free Quantification (LFQ)"
author: "Christian Panse / Jonas Grossmann"
date: "2016/01/24"
output: 
  - slidy_presentation
  - rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{LabelFreeQuantification}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r echo=FALSE}
plot.psmSet <- function (x, iRTpeptides = specL::iRTpeptides, ...) 
{
    rt <- unlist(lapply(x, function(x) {
        x$rt
    }))
    pepmass <- unlist(lapply(x, function(xx) {
        xx$pepmass
    }))
    peptide <- unlist(lapply(x, function(xx) {
        xx$peptideSequence
    }))
    idx.iRT <- which(peptide %in% iRTpeptides$peptide)
    charge <- unlist(lapply(x, function(xx) {
        xx$charge
    }))
    filename <- as.numeric(as.factor(unlist(lapply(x, function(xx) {
        xx$fileName
    }))))
    plot(pepmass ~ rt, pch = filename, col = charge, main = "LCMS map", 
        xlab = "retention time", ylab = "peptide mass", ...)
    cc <- sort(unique(charge))
    legend("topleft", "iRT peptides", pch = 22)
    legend("left", paste(cc, "+", sep = ""), col = cc, pch = 22, 
        title = "charge")
    text(rt, pepmass, 1:length(rt), pos = 3, col = charge, cex = 0.5)
    fn <- unique(unlist(lapply(x, function(xx) {
        xx$fileName
    })))
    n <- nchar(fn)
    #legend("bottomright", substr(fn, n - 25, n), pch = unique(filename), 
    #    cex = 1, title = "input file names")
    points(rt[idx.iRT], pepmass[idx.iRT], pch = 22, cex = 2)
}
```

```{r}
#library(specL)
library(ISCB2017)
```


# consideration

```{r}
#filename <- paste(path.package("ISCB2017"), "extdata/proteotypic_peptides.txt", sep='/')
#P <- read.table(filename, col.names=c('protein','peptide','pim'))

#load("data/F244088f.RData")
```

# plot filtered LCMS map
```{r}
data(F244088f)

plot.psmSet(F244088f)
```

```{r fig.retina=3}
# xyplot(pim ~ ssrc | protein, group=protein, data=P)
```

## xic

get RT
```{r fig.retina=3}
X <- do.call('rbind', 
             lapply(F244088f,
                    function(x){data.frame(peptide=x$peptideSequence,
                        rtms2=x$rtinseconds/60)}))
XIC.id <- merge(XIC, X, by='peptide')

library(lattice)
t <- trellis.par.get()
t$superpose.line$alpha<-0.1
t$superpose.symbol$alpha<-0.1
trellis.par.set(t)
lapply(unique(XIC$protein), function(p){
  XIC.f <- XIC.id[XIC.id$protein == p,]
  xyplot(count ~ rt | peptide * protein, 
         group=filename, 
         data=XIC.f, type='h', subset=protein==p,
      layout=c(1, 4))})
```

```{r}
eps <- 0.5

XIC.f <- XIC.id[XIC.id$rtms2 - eps < XIC.id$rt & XIC.id$rt < XIC.id$rtms2 + eps, ] 


#library(lattice())
#xyplot(log(count,2) ~ rt|protein ,group=charge, data=XIC.f[grepl("20161115_12_GE1_b.raw", XIC.f$filename),], type='h')



```

```{r}
XIC.max <- aggregate(count ~ protein + peptide + charge + filename, 
                     data=XIC.f, FUN=max)

bwplot( (log(count)-mean(log(count)))/sd(log(count)) ~ filename|protein,data=XIC.max, layout=c(1,4), scales = list(x = list(rot = 45)))

  
M <- reshape2::dcast(XIC.max, formula = protein + peptide + charge ~ filename)
image(t(as.matrix(asinh(M[,4:16]))))

rownames(M) <-paste(M[,1], M[,2], M[,3])
M[,1:3] <- NULL
M[is.na(M)] <- 0

library(gplots)
heatmap.2(asinh(as.matrix((MM))), margins = c(20,15), trace = "none")
#XIC.max <- merge(XIC, XIC.max, by.x=names(XIC.max), by.y = names(XIC.max))
```

# RT normalization


http://bioconductor.org/packages/release/data/experiment/vignettes/msqc1/inst/doc/chromatography.html

# Two Group
```{r fig.retina=3}
#S <- read.table("data/p1946_prx.tsv", sep='\t', header=TRUE)
gg <- c(rep('G', 6), rep('GE', 6))
dim(prxmq)
table(gg)

op <- par(mfrow=c(1,3))
# example 0
idx <- 2
x <- log(unlist(prxmq[idx, ]),2)
boxplot(x ~ gg, main=row.names(prxmq)[idx])
t.test(x ~ gg,  alternative = "two.sided")

# example 1
idx <- which(row.names(prxmq) == "sp|P00331|ADH2_YEAST")
x <- log(unlist(prxmq[idx, ]),2)
boxplot(x ~ gg, main=row.names(prxmq)[idx])
t.test(x ~ gg,  alternative = "two.sided")

#example 2
idx <- which(row.names(prxmq) == "sp|P33302|PDR5_YEAST")
x <- log(unlist(prxmq[idx, ]),2)
boxplot(x ~ gg, main=row.names(prxmq)[idx])
t.test(x ~ gg,  alternative = "two.sided")
```


```{r}
expression_analysis <- function(S, groups){
  S.t.test <- lapply(1:nrow(S), function(idx){
    x <- unlist(S[idx, ])
    x[x==0] <- NA
    if (min(aggregate(x, by=list(groups), function(x){sum(!is.na(x))})$x) > 5){
      t <- t.test(log(x, 2) ~ groups, alternative = "two.sided")
      r <- cbind(FC = diff(t$estimate), p.value = t$p.value, idx=idx)
      row.names(r) <- row.names(S)[idx]
      r
    }else{NULL}
  })
  
  S.t.test <- as.data.frame(do.call('rbind', S.t.test))
 
  S.t.test
}


S.t.test <- expression_analysis(prxmq, gg)
head(S.t.test)
```

# volcano plot - p.value vs FC

```{r fig.retina=3}
plot_volcano <- function(S.t.test){
  plot(-log(p.value,10) ~ FC, data=S.t.test, 
       main="volcano plot",
       sub="p1946 prx")
  abline(v=c(-0.5,0.5), col='grey')
  abline(h=-log(0.025, 10), col='grey')
  
  points(-log(p.value,10) ~ FC, 
         data=S.t.test[abs(S.t.test$FC)>0.5 & S.t.test$p.value<0.025,], 
         col='red',cex=0.5)
  
  points(-log(p.value,10) ~ FC,
         data=S.t.test[grepl('ZZ', rownames(S.t.test)),],
         col='cyan')
  
  points(-log(p.value,10) ~ FC,
         data=S.t.test[grepl('REV', rownames(S.t.test)),],
         cex=2, lwd=2,
         col='green')
}

plot_volcano(S.t.test)
```

# What happen if you mess up your annotation?
```{r}
random_swap <- function(x){
   a <- sample(length(x),2)
   tmp <- x[a[1]]
   x[a[1]] <- x[a[2]]
   x[a[2]] <- tmp
  
   return(x)
   }
```

```{r fig.retina=5}
op<-par(mfrow=c(2,2))
plot_volcano(S.t.test)
(gg <- random_swap(gg)); S.t.test <- expression_analysis(prxmq, gg); plot_volcano(S.t.test)
(gg <- random_swap(gg)); S.t.test <- expression_analysis(prxmq, gg); plot_volcano(S.t.test)
(gg <- random_swap(gg)); S.t.test <- expression_analysis(prxmq, gg); plot_volcano(S.t.test)
```

* a viewpoint on volcano plot:
Uses and misuses of the fudge factor in
quantitative discovery proteomics, Proteomics 2016, 16, 1955–1960 
http://onlinelibrary.wiley.com/doi/10.1002/pmic.201600132/epdf
