---
title: "20161216_CHE434 live demo"
author: "Christian Panse"
date: "12/12/2016"

output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

random_swap <- function(x){
   a <- sample(length(x),2)
   tmp <- x[a[1]]
   x[a[1]] <- x[a[2]]
   x[a[2]] <- tmp
  
   return(x)
   }
```

# FASTA - get current SwissProt

```bash
curl ftp://ftp.uniprot.org/pub/databases/uniprot/\
current_release/knowledgebase/complete/uniprot_sprot.fasta.gz \
| gunzip -c \
> swissprot
```

# Top ten organisms having the largest number of entries in swissprot
```base
grep "^>" < swissprot \
| awk '$1~/_/{print $1}' \
| awk -F"_" '{h[$NF]++}END{for (i in h){print i" "h[i]}}' \
| sort -k2 -g -r -S128M \
| head -n 10
```

# MS detectable peptides

tryptic digest rule: cut after R or K if the C-term. residue is not P.
```bash
grep "^>sp|P21781|FGF7_HUMAN" -A 5 < swissprot \
| fcat \
| digest \
| pim  \
| awk -F";" '600<$2 && $2<6000{print }'
```



# CRAN package protViz

* install R
http://stat.ethz.ch/CRAN/

* install protViz
https://CRAN.R-project.org/package=protViz

```{R}
library(protViz)
```

# Compute fragmention table of 'EGVNDNEEGFFSAR'

```{R}
fragmentIon('EGVNDNEEGFFSAR')
```


# Plot tandem MS

```{R}
#source('F161375_query160.R')
load("F161375.RData")
plot(F161375[[160]]$mZ, F161375[[160]]$intensity, type='h')
```

# Label tandem MS

```{r fig.retina=3}
peakplot(peptide=F161375[[160]]$peptideSequence, 
         spec=F161375[[160]],
         FUN=function(b,y){
           return (list(y=y))
         })
```
