---
title: "Label Free Quantification (LFQ)"
author: "Christian Panse / Jonas Grossmann"
date: "2016/01/24"
output: 
  - slidy_presentation
  - rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{LabelFreeQuantification}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}

library(ISCB2017)
```

```{r echo=FALSE}
X <- do.call('rbind', 
             lapply(F244088f,
                    function(x){data.frame(peptide=x$peptideSequence,
                        rtms2=x$rtinseconds/60)}))

PP<-unique(X$peptide)
```

```{r}

mascotfiles <- c('F247106', 'F247107', 'F247108', 'F247110', 'F247111', 'F247112', 'F247113', 'F247114', 'F247115', 'F247116', 'F247117', 'F247118', 'F247120')

rrr <- lapply(mascotfiles, function(fn){
  load(paste("data/", fn, '.RData', sep=''))
 lapply(get(fn), function(x){
  if(x$peptideSequence %in% PP){
    title <- unlist(strsplit(as.character(x$title), split='/'))
    data.frame(peptide=x$peptideSequence, 
               rt=x$rtinseconds, 
               title = title[length(title)])
    } else{NULL}
  })

rr <- do.call('rbind', r[which(!sapply(r, is.null))])
})
```

